version: '3'
services:
  nextjs-docker:
    image: cracoidic/nextjs:0.1
    container_name: nextjs_sample_development
    ports:
      - 30000:3000
    volumes:
      - ./:/usr/src/app
      - vol_node_modules:/usr/src/app/node_modules
      - vol_next:/usr/src/app/.next
    command: bash -c "npm install && npm run dev"
volumes:
  vol_next:
    driver: local
  vol_node_modules:
    driver: local
